urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('detalle_producto/<str:Nombre>/', views.detalle_producto, name="detalle_producto"),
    path('carrito/', views.carrito, name="carrito"),
    path('iniciar_sesion/', views.iniciar_sesion, name="iniciar_sesion"),
    path('perfil_usuario/<str:nombre_de_usuario>/', views.perfil_usuario, name='perfil_usuario'),
    path('registrar_cliente/', views.registrar_cliente, name='registrar_cliente'),
    path('cerrar_sesion/', views.cerrar_sesion, name='cerrar_sesion'),
    path('historial_pedidos/', views.historial_pedidos, name="historial_pedidos"),
    path('editar_perfil/<str:nombre_de_usuario>/', views.editar_perfil, name="editar_perfil"),
    path('mostrar_productos/<str:categoria>/', views.mostrar_productos, name='mostrar_productos'),
    path('agregar_al_carrito/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('actualizar-carrito/', views.actualizar_carrito, name='actualizar_carrito'),
    path('comprar_productos/', views.comprar_productos, name='comprar_productos'),
    path('PoliticaPrivacidad/', views.PoliticaPrivacidad, name='PoliticaPrivacidad'),
    path('TerminosCondiciones/', views.TerminosCondiciones, name='TerminosCondiciones'),
    path('final_compra/', views.final_compra, name='final_compra'),
    path('generar_factura_pdf/', views.generar_factura_pdf, name='generar_factura_pdf'),
    path('generar_ticket_pdf/', views.generar_ticket_pdf, name='generar_ticket_pdf')
]

models.py
from django.db import models

# Create your models here.
class Producto(models.Model):
    Nombre = models.CharField(max_length=100)
    ImagenProducto = models.ImageField(upload_to='product_images/', blank=True, null=True)
    Descripcion = models.TextField()
    Precio = models.DecimalField(max_digits=10, decimal_places=2)
    Categoria = models.CharField(max_length=100, default="Otro")
    Cantidad_en_stock = models.IntegerField(default=0)

    def __str__(self):
        return self.Nombre

    def reducir_stock(self, cantidad):
        self.cantidad_en_stock -= cantidad
        self.save()

    def aumentar_stock(self, cantidad):
        self.cantidad_en_stock += cantidad
        self.save()

class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    telefono = models.CharField(max_length=15)
    password = models.CharField(max_length=128,default='1234')
    direccion = models.TextField()

    def __str__(self):
        return self.nombre

class Pedido(models.Model):
    cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE)
    productos = models.ManyToManyField('Producto', through='ItemPedido')
    fecha_pedido = models.DateTimeField(auto_now_add=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)

    # Información de la tarjeta del cliente
    numero_tarjeta = models.CharField(max_length=16)  # El número de la tarjeta (generalmente 16 dígitos)
    fecha_vencimiento = models.DateField(null=True)  # La fecha de vencimiento de la tarjeta
    nombre_titular = models.CharField(max_length=100,null=True)  # El nombre del titular de la tarjeta

    # Dirección de envío
    direccion_envio = models.TextField(default='Dirección predeterminada')  # La dirección a la que se enviarán los productos

    def __str__(self):
        return f'Pedido {self.id} - Cliente: {self.cliente.nombre}'

class ItemPedido(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'Producto: {self.producto.Nombre} - Cantidad: {self.cantidad}'

class SeguimientoPedido(models.Model):
    ESTADOS = (
        ('Pendiente', 'Pendiente'),
        ('En camino', 'En camino'),
        ('Entregado', 'Entregado'),
    )
    pedido = models.OneToOneField(Pedido, on_delete=models.CASCADE, related_name='seguimiento')
    estado = models.CharField(max_length=20, choices=ESTADOS, default='Pendiente')
    fecha = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Seguimiento Pedido {self.pedido.id} - Estado: {self.estado}'

templates/editar_perfil.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Perfil</title> 
    <link rel="stylesheet" href="{% static 'editar_perfil.css'%}">
    <link rel="icon" type="image/png" href="{% static 'img/IT_SOLUTIONS.png' %}">
</head>
<body>
    <header>
        <a href="{% url 'index' %}">
            <img src="{% static 'img/IT_SOLUTIONS.png' %}" alt="logo">
        </a>
        <nav>
            <ul>
                <li class="move-right">
                    <a href="{% url 'cerrar_sesion' %}" class="delay-link">
                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-door-open" viewBox="0 0 16 16">
                            <path d="M8.5 10c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1"/>
                            <path d="M10.828.122A.5.5 0 0 1 11 .5V1h.5A1.5 1.5 0 0 1 13 2.5V15h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V1.5a.5.5 0 0 1 .43-.495l7-1a.5.5 0 0 1 .398.117M11.5 2H11v13h1V2.5a.5.5 0 0 0-.5-.5M4 1.934V15h6V1.077z"/>
                        </svg>
                    </a>
                </li>
            </ul>
        </nav>
    </header>

    <div class="container1">
        <h1>Editar Perfil</h1>
        <form id="edit-profile-form" action="{% url 'editar_perfil' nombre_de_usuario=cliente.nombre %}" method="POST">
            {% csrf_token %}
            <label for="nombre">Nombre:</label>
            <input type="text" id="nombre" name="nombre" value="{{ cliente.nombre }}" required>
            
            <label for="email">Correo Electrónico:</label>
            <input type="email" id="email" name="email" value="{{ cliente.email }}" required>
    
            <label for="telefono">Telefono:</label>
            <input type="telefono" id="telefono" name="telefono" value="{{ cliente.telefono }}" required>
            
            <label for="direccion">Direccion:</label>
            <input type="direccion" id="direccion" name="direccion" value="{{ cliente.direccion }}" required>

            <label for="password">Contraseña:</label>
            <input type="password" id="password" name="password" value="{{ cliente.password }}">
            
            <div class="btn-container">
                <button type="submit" class="btn">Guardar Cambios</button>
                <a href="{% url 'perfil_usuario' nombre_de_usuario=cliente.nombre %}" class="btn">Cancelar</a>
            </div>
        </form>
    </div>

    <footer>
        <div class="footer-container">
            <div class="contactos">
                <h3>Contacto</h3>
                <ul>
                    <p><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16">
                        <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.6 17.6 0 0 0 4.168 6.608 17.6 17.6 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.68.68 0 0 0-.58-.122l-2.19.547a1.75 1.75 0 0 1-1.657-.459L5.482 8.062a1.75 1.75 0 0 1-.46-1.657l.548-2.19a.68.68 0 0 0-.122-.58zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.68.68 0 0 0 .178.643l2.457 2.457a.68.68 0 0 0 .644.178l2.189-.547a1.75 1.75 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.6 18.6 0 0 1-7.01-4.42 18.6 18.6 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877z"/>
                      </svg>: 123-456-789</p>
                    <li><a href="mailto:itsolutionsstore2024@gmail.com"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-envelope-at" viewBox="0 0 16 16">
                        <path d="M2 2a2 2 0 0 0-2 2v8.01A2 2 0 0 0 2 14h5.5a.5.5 0 0 0 0-1H2a1 1 0 0 1-.966-.741l5.64-3.471L8 9.583l7-4.2V8.5a.5.5 0 0 0 1 0V4a2 2 0 0 0-2-2zm3.708 6.208L1 11.105V5.383zM1 4.217V4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v.217l-7 4.2z"/>
                        <path d="M14.247 14.269c1.01 0 1.587-.857 1.587-2.025v-.21C15.834 10.43 14.64 9 12.52 9h-.035C10.42 9 9 10.36 9 12.432v.214C9 14.82 10.438 16 12.358 16h.044c.594 0 1.018-.074 1.237-.175v-.73c-.245.11-.673.18-1.18.18h-.044c-1.334 0-2.571-.788-2.571-2.655v-.157c0-1.657 1.058-2.724 2.64-2.724h.04c1.535 0 2.484 1.05 2.484 2.326v.118c0 .975-.324 1.39-.639 1.39-.232 0-.41-.148-.41-.42v-2.19h-.906v.569h-.03c-.084-.298-.368-.63-.954-.63-.778 0-1.259.555-1.259 1.4v.528c0 .892.49 1.434 1.26 1.434.471 0 .896-.227 1.014-.643h.043c.118.42.617.648 1.12.648m-2.453-1.588v-.227c0-.546.227-.791.573-.791.297 0 .572.192.572.708v.367c0 .573-.253.744-.564.744-.354 0-.581-.215-.581-.8Z"/>
                      </svg></a></li>
                </ul>
            </div>
            <div class="redes-sociales">
                <h3>Redes Sociales</h3>
                <ul>
                    <li><a href="https://www.facebook.com/share/7zhAjmK73KkkeQXp/?mibextid=qi2Omg" target="_blank">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/>
                          </svg></a></li>
                    <li><a href="https://x.com/ITSolutionStore?t=vsRAMYf0ubkfNTjDdTIZGA&s=08" target="_blank"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-twitter-x" viewBox="0 0 16 16">
                        <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/>
                      </svg></a></li>
                    <li><a href="https://www.instagram.com/it_solutions_store?igsh=MTZ5b3RjdnduM2RnbA==" target="_blank"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                        <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
                      </svg></a></li>
                </ul>
            </div>
        </div>
        <div class="terminos">
            <ul>
                <p>Todos los derechos reservados &copy; 2024</p>
                <li><a href="{% url 'PoliticaPrivacidad' %}">Política de Privacidad</a></li>
                <li><a href="{% url 'TerminosCondiciones' %}">Términos y Condiciones</a></li>
            </ul>
        </div>
    </footer>

</body>
</html>

templates/historial_pedidos.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Historial de Pedidos</title>
    <link rel="stylesheet" href="{% static 'historial.css'%}">
    <link rel="icon" type="image/png" href="{% static 'img/IT_SOLUTIONS.png' %}">
</head>
<body>
    <header>
        <a href="{% url 'index' %}">
            <img src="{% static 'img/IT_SOLUTIONS.png' %}" alt="logo">
        </a>
        <nav>
            <ul>
                <li class="move-right">
                    <a href="{% url 'cerrar_sesion' %}" class="delay-link">
                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-door-open" viewBox="0 0 16 16">
                            <path d="M8.5 10c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1"/>
                            <path d="M10.828.122A.5.5 0 0 1 11 .5V1h.5A1.5 1.5 0 0 1 13 2.5V15h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V1.5a.5.5 0 0 1 .43-.495l7-1a.5.5 0 0 1 .398.117M11.5 2H11v13h1V2.5a.5.5 0 0 0-.5-.5M4 1.934V15h6V1.077z"/>
                        </svg>
                    </a>
                </li>
            </ul>
        </nav>
    </header>

    <div class="container2">
    <h1>Historial de Pedidos</h1>
    <div class="purchase-history">
        {% for pedido in pedidos %}
            <div class="purchase-item">
                <div class="purchase-info">
                    <h2>Pedido: {{ pedido.id }}</h2>
                    <p>Fecha del Pedido: {{ pedido.fecha_pedido|date:"d/m/Y" }}</p>
                    <p>Total del Pedido: ${{ pedido.total }}</p>
                    <h3>Detalles del Pedido:</h3>
                    
                    {% for item in pedido.itempedido_set.all %}
                        <p>Producto: {{ item.producto.Nombre }}</p>
                        <p>Cantidad: {{ item.cantidad }}</p>
                        <p>Precio Unitario: ${{ item.precio_unitario }}</p>
                    {% endfor %}
                
                    <h3>Dirección de Envío:</h3>
                    <p>{{ pedido.direccion_envio }}</p>
                    <h3>Información de Pago:</h3>
                    <p>Número de Tarjeta: **** **** **** {{ pedido.numero_tarjeta|slice:"-4:" }}</p>
                    <p>Fecha de Expiración: {{ pedido.fecha_vencimiento|date:"m/y" }}</p>
                    <p>Nombre del Titular: {{ pedido.nombre_titular }}</p>

                    <h3>Seguimiento del Pedido:</h3>
                    <p>Estado: {{ pedido.seguimiento.estado }}</p>
                    <p>Fecha de Seguimiento: {{ pedido.seguimiento.fecha|date:"d/m/Y H:i:s" }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

    <footer>
        <div class="footer-container">
            <div class="contactos">
                <h3>Contacto</h3>
                <ul>
                    <p><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16">
                        <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.6 17.6 0 0 0 4.168 6.608 17.6 17.6 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.68.68 0 0 0-.58-.122l-2.19.547a1.75 1.75 0 0 1-1.657-.459L5.482 8.062a1.75 1.75 0 0 1-.46-1.657l.548-2.19a.68.68 0 0 0-.122-.58zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.68.68 0 0 0 .178.643l2.457 2.457a.68.68 0 0 0 .644.178l2.189-.547a1.75 1.75 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.6 18.6 0 0 1-7.01-4.42 18.6 18.6 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877z"/>
                      </svg>: 123-456-789</p>
                    <li><a href="mailto:itsolutionsstore2024@gmail.com"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-envelope-at" viewBox="0 0 16 16">
                        <path d="M2 2a2 2 0 0 0-2 2v8.01A2 2 0 0 0 2 14h5.5a.5.5 0 0 0 0-1H2a1 1 0 0 1-.966-.741l5.64-3.471L8 9.583l7-4.2V8.5a.5.5 0 0 0 1 0V4a2 2 0 0 0-2-2zm3.708 6.208L1 11.105V5.383zM1 4.217V4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v.217l-7 4.2z"/>
                        <path d="M14.247 14.269c1.01 0 1.587-.857 1.587-2.025v-.21C15.834 10.43 14.64 9 12.52 9h-.035C10.42 9 9 10.36 9 12.432v.214C9 14.82 10.438 16 12.358 16h.044c.594 0 1.018-.074 1.237-.175v-.73c-.245.11-.673.18-1.18.18h-.044c-1.334 0-2.571-.788-2.571-2.655v-.157c0-1.657 1.058-2.724 2.64-2.724h.04c1.535 0 2.484 1.05 2.484 2.326v.118c0 .975-.324 1.39-.639 1.39-.232 0-.41-.148-.41-.42v-2.19h-.906v.569h-.03c-.084-.298-.368-.63-.954-.63-.778 0-1.259.555-1.259 1.4v.528c0 .892.49 1.434 1.26 1.434.471 0 .896-.227 1.014-.643h.043c.118.42.617.648 1.12.648m-2.453-1.588v-.227c0-.546.227-.791.573-.791.297 0 .572.192.572.708v.367c0 .573-.253.744-.564.744-.354 0-.581-.215-.581-.8Z"/>
                      </svg></a></li>
                </ul>
            </div>
            <div class="redes-sociales">
                <h3>Redes Sociales</h3>
                <ul>
                    <li><a href="https://www.facebook.com/share/7zhAjmK73KkkeQXp/?mibextid=qi2Omg" target="_blank">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/>
                          </svg></a></li>
                    <li><a href="https://x.com/ITSolutionStore?t=vsRAMYf0ubkfNTjDdTIZGA&s=08" target="_blank"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-twitter-x" viewBox="0 0 16 16">
                        <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/>
                      </svg></a></li>
                    <li><a href="https://www.instagram.com/it_solutions_store?igsh=MTZ5b3RjdnduM2RnbA==" target="_blank"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                        <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
                      </svg></a></li>
                </ul>
            </div>
        </div>
        <div class="terminos">
            <ul>
                <p>Todos los derechos reservados &copy; 2024</p>
                <li><a href="{% url 'PoliticaPrivacidad' %}">Política de Privacidad</a></li>
                <li><a href="{% url 'TerminosCondiciones' %}">Términos y Condiciones</a></li>
            </ul>
        </div>
    </footer>

    <script>
        function regresarAIndex() {
            window.location.href = 'index.html'; // Cambia 'index.html' por la ruta de tu página de inicio
        }
    </script>

</body>
</html>